# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/wsl/uni/TDP005/tdp005_objektorienterat_system

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/wsl/uni/TDP005/tdp005_objektorienterat_system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/wsl/uni/TDP005/tdp005_objektorienterat_system/CMakeFiles /mnt/c/wsl/uni/TDP005/tdp005_objektorienterat_system/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/wsl/uni/TDP005/tdp005_objektorienterat_system/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ballgame

# Build rule for target.
ballgame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ballgame
.PHONY : ballgame

# fast build rule for target.
ballgame/fast:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/build
.PHONY : ballgame/fast

Ball.o: Ball.cpp.o

.PHONY : Ball.o

# target to build an object file
Ball.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Ball.cpp.o
.PHONY : Ball.cpp.o

Ball.i: Ball.cpp.i

.PHONY : Ball.i

# target to preprocess a source file
Ball.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Ball.cpp.i
.PHONY : Ball.cpp.i

Ball.s: Ball.cpp.s

.PHONY : Ball.s

# target to generate assembly for a file
Ball.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Ball.cpp.s
.PHONY : Ball.cpp.s

Dead_Zone.o: Dead_Zone.cpp.o

.PHONY : Dead_Zone.o

# target to build an object file
Dead_Zone.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Dead_Zone.cpp.o
.PHONY : Dead_Zone.cpp.o

Dead_Zone.i: Dead_Zone.cpp.i

.PHONY : Dead_Zone.i

# target to preprocess a source file
Dead_Zone.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Dead_Zone.cpp.i
.PHONY : Dead_Zone.cpp.i

Dead_Zone.s: Dead_Zone.cpp.s

.PHONY : Dead_Zone.s

# target to generate assembly for a file
Dead_Zone.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Dead_Zone.cpp.s
.PHONY : Dead_Zone.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

Movable.o: Movable.cpp.o

.PHONY : Movable.o

# target to build an object file
Movable.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Movable.cpp.o
.PHONY : Movable.cpp.o

Movable.i: Movable.cpp.i

.PHONY : Movable.i

# target to preprocess a source file
Movable.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Movable.cpp.i
.PHONY : Movable.cpp.i

Movable.s: Movable.cpp.s

.PHONY : Movable.s

# target to generate assembly for a file
Movable.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Movable.cpp.s
.PHONY : Movable.cpp.s

Physics_Object.o: Physics_Object.cpp.o

.PHONY : Physics_Object.o

# target to build an object file
Physics_Object.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Physics_Object.cpp.o
.PHONY : Physics_Object.cpp.o

Physics_Object.i: Physics_Object.cpp.i

.PHONY : Physics_Object.i

# target to preprocess a source file
Physics_Object.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Physics_Object.cpp.i
.PHONY : Physics_Object.cpp.i

Physics_Object.s: Physics_Object.cpp.s

.PHONY : Physics_Object.s

# target to generate assembly for a file
Physics_Object.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Physics_Object.cpp.s
.PHONY : Physics_Object.cpp.s

Play_State.o: Play_State.cpp.o

.PHONY : Play_State.o

# target to build an object file
Play_State.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Play_State.cpp.o
.PHONY : Play_State.cpp.o

Play_State.i: Play_State.cpp.i

.PHONY : Play_State.i

# target to preprocess a source file
Play_State.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Play_State.cpp.i
.PHONY : Play_State.cpp.i

Play_State.s: Play_State.cpp.s

.PHONY : Play_State.s

# target to generate assembly for a file
Play_State.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Play_State.cpp.s
.PHONY : Play_State.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Player.cpp.s
.PHONY : Player.cpp.s

Point_Zone.o: Point_Zone.cpp.o

.PHONY : Point_Zone.o

# target to build an object file
Point_Zone.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Point_Zone.cpp.o
.PHONY : Point_Zone.cpp.o

Point_Zone.i: Point_Zone.cpp.i

.PHONY : Point_Zone.i

# target to preprocess a source file
Point_Zone.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Point_Zone.cpp.i
.PHONY : Point_Zone.cpp.i

Point_Zone.s: Point_Zone.cpp.s

.PHONY : Point_Zone.s

# target to generate assembly for a file
Point_Zone.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Point_Zone.cpp.s
.PHONY : Point_Zone.cpp.s

Power_Up.o: Power_Up.cpp.o

.PHONY : Power_Up.o

# target to build an object file
Power_Up.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Power_Up.cpp.o
.PHONY : Power_Up.cpp.o

Power_Up.i: Power_Up.cpp.i

.PHONY : Power_Up.i

# target to preprocess a source file
Power_Up.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Power_Up.cpp.i
.PHONY : Power_Up.cpp.i

Power_Up.s: Power_Up.cpp.s

.PHONY : Power_Up.s

# target to generate assembly for a file
Power_Up.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Power_Up.cpp.s
.PHONY : Power_Up.cpp.s

Randomizer.o: Randomizer.cpp.o

.PHONY : Randomizer.o

# target to build an object file
Randomizer.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Randomizer.cpp.o
.PHONY : Randomizer.cpp.o

Randomizer.i: Randomizer.cpp.i

.PHONY : Randomizer.i

# target to preprocess a source file
Randomizer.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Randomizer.cpp.i
.PHONY : Randomizer.cpp.i

Randomizer.s: Randomizer.cpp.s

.PHONY : Randomizer.s

# target to generate assembly for a file
Randomizer.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Randomizer.cpp.s
.PHONY : Randomizer.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/State.cpp.s
.PHONY : State.cpp.s

Stationary.o: Stationary.cpp.o

.PHONY : Stationary.o

# target to build an object file
Stationary.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Stationary.cpp.o
.PHONY : Stationary.cpp.o

Stationary.i: Stationary.cpp.i

.PHONY : Stationary.i

# target to preprocess a source file
Stationary.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Stationary.cpp.i
.PHONY : Stationary.cpp.i

Stationary.s: Stationary.cpp.s

.PHONY : Stationary.s

# target to generate assembly for a file
Stationary.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Stationary.cpp.s
.PHONY : Stationary.cpp.s

Triple_Ball.o: Triple_Ball.cpp.o

.PHONY : Triple_Ball.o

# target to build an object file
Triple_Ball.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Triple_Ball.cpp.o
.PHONY : Triple_Ball.cpp.o

Triple_Ball.i: Triple_Ball.cpp.i

.PHONY : Triple_Ball.i

# target to preprocess a source file
Triple_Ball.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Triple_Ball.cpp.i
.PHONY : Triple_Ball.cpp.i

Triple_Ball.s: Triple_Ball.cpp.s

.PHONY : Triple_Ball.s

# target to generate assembly for a file
Triple_Ball.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/Triple_Ball.cpp.s
.PHONY : Triple_Ball.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ballgame.dir/build.make CMakeFiles/ballgame.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ballgame"
	@echo "... edit_cache"
	@echo "... Ball.o"
	@echo "... Ball.i"
	@echo "... Ball.s"
	@echo "... Dead_Zone.o"
	@echo "... Dead_Zone.i"
	@echo "... Dead_Zone.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... Movable.o"
	@echo "... Movable.i"
	@echo "... Movable.s"
	@echo "... Physics_Object.o"
	@echo "... Physics_Object.i"
	@echo "... Physics_Object.s"
	@echo "... Play_State.o"
	@echo "... Play_State.i"
	@echo "... Play_State.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Point_Zone.o"
	@echo "... Point_Zone.i"
	@echo "... Point_Zone.s"
	@echo "... Power_Up.o"
	@echo "... Power_Up.i"
	@echo "... Power_Up.s"
	@echo "... Randomizer.o"
	@echo "... Randomizer.i"
	@echo "... Randomizer.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... Stationary.o"
	@echo "... Stationary.i"
	@echo "... Stationary.s"
	@echo "... Triple_Ball.o"
	@echo "... Triple_Ball.i"
	@echo "... Triple_Ball.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

